language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
install:
  - npm install
  # - yarn test
script:
  - npm run bundle
deploy:
  provider: s3
  access_key_id: AKIAJLPX77ICVZALUXEA
  secret_access_key:
    secure: LS44LXmdoPByNPmPtiLGn9rcTl9Z9Sd1ZpkxGa/CObB6DYTgJM5lL3itrIna4d5/jTlFNA79xg3mqgg3eOgeYJV+tu5sxoLifkcNyALPIdy2oNQNNnTCUNnS1Lh5WoqnjkrVRIez3HuGx60fI0Ydqpz38ySJG6YgK5kxpglTij5qJlbzcF8qkCHoXaWmz8ZmqEyhVetfUGu2sVov6lCmIEhNxZX9CS00wRderTFY19r3D3d7hFEjcc50ytci3R5HIH6FR9EBvloVZ7AaQNU2bv5xd52eqKMLAlvHelRn5bDL1VIICuDzUgRwUmr98e6GZRo44iVcp8ww1hdtqlWEuVgwU6c3jNUANYjeRWfRQ57np4jNSnHO49vTCMgYUgsNlUwq2tsGAIC9g2CEjT3hCvfYOUYV5YJmZvPDcxo/5T5sdDQRskUHN1w6cEoiaaqtgU+AYnE2Y4XUGGgX7MqFCq6LsCOEGIDYO6VjrNL+Nbq1JR3pVIDyRiZ7g7g+1HMlFPmxPe8pUCNRcdW7104dEJ2YAnt26c/C9T9gEbo2yw2zJ9xIjIXbraRYHlXuysV9sYddhcr6OPwet3LEbf46YjnZXGr3b0vYWxM3haKt+EKaV4R5RmbzQmUHS3Leldux+r1Fjg28uNKbVfZn9EKGcBtZQTc1H1fwz7cH2iOHd7I=
  bucket: wordlistdutchwords
  local-dir: dist
  acl: public_read
  region: eu-west-1
  skip_cleanup: true
branches:
  only:
    - master
