language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
install:
  - npm install
  # - yarn test
script:
  - npm run bundle
deploy:
  provider: s3
  access_key_id: AKIAYEEKD67L2DTDCVAP
  secret_access_key: $SECRET
  bucket: wordlistdutchwords
  local-dir: dist
  acl: public_read
  region: eu-west-1
  skip_cleanup: true
branches:
  only:
    - master
